export enum PRODUCTS {
  GET_LIST_REQUEST = "PRODUCTS/GET_LIST/REQUEST",
  GET_LIST_SUCCESS = "PRODUCTS/GET_LIST/SUCCESS",
  GET_LIST_FAILURE = "PRODUCTS/GET_LIST/FAILURE",

  GET_REQUEST = "PRODUCTS/GET/REQUEST",
  GET_SUCCESS = "PRODUCTS/GET/SUCCESS",
  GET_FAILURE = "PRODUCTS/GET/FAILURE",

  CREATE_REQUEST = "PRODUCTS/CREATE/REQUEST",
  CREATE_SUCCESS = "PRODUCTS/CREATE/SUCCESS",
  CREATE_FAILURE = "PRODUCTS/CREATE/FAILURE",

  UPDATE_REQUEST = "PRODUCTS/UPDATE/REQUEST",
  UPDATE_SUCCESS = "PRODUCTS/UPDATE/SUCCESS",
  UPDATE_FAILURE = "PRODUCTS/UPDATE/FAILURE",

  DELETE_REQUEST = "PRODUCTS/DELETE/REQUEST",
  DELETE_SUCCESS = "PRODUCTS/DELETE/SUCCESS",
  DELETE_FAILURE = "PRODUCTS/DELETE/FAILURE",
}
